#pragma once

#include "Runtime/Core/Gear.h"

NAMESPACE_START(RHI)

DECLARE_SMART_PTR(IBuffer)
DECLARE_SMART_PTR(IShader)
DECLARE_SMART_PTR(IImage)
DECLARE_SMART_PTR(ISampler)
DECLARE_SMART_PTR(ICommandBuffer)
DECLARE_SMART_PTR(ICommandBufferPool)
DECLARE_SMART_PTR(IInputLayout)
DECLARE_SMART_PTR(IPipeline)
DECLARE_SMART_PTR(IFrameBuffer)
DECLARE_SMART_PTR(IRenderPass)
DECLARE_SMART_PTR(IDevice)
DECLARE_SMART_PTR(IRenderer)

NAMESPACE_END(RHI)


